"""add is_active to Cart

Revision ID: 3a8f8f1c11f0
Revises: 939727cc54fa
Create Date: 2026-02-28 12:37:49.631386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a8f8f1c11f0'
down_revision: Union[str, Sequence[str], None] = '939727cc54fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'is_active')
    # ### end Alembic commands ###
